INSERT INTO Employee0015 VALUES
('John', 'B.', 'Smith', 1, NULL, 'JMI, New Delhi', 'M', 10000, 2, 1),
('Ashhar', NULL, 'Hasan', 2, NULL, 'Texas, HO', 'M', 20000, NULL, 1),
('Fatima', NULL, 'Munawwar', 3, NULL, 'New Delhi', 'F', 10000, 2, 5);

INSERT INTO Department0015 VALUES
('CS', 1, 2, NULL),
('Administration', 5, 3, NULL);

INSERT INTO Dept_Locations0015 VALUES
(1, 'Houston'),
(5, 'New Delhi');

INSERT INTO Project0015 VALUES
('ProjectX', 1, 'New Delhi', 1),
('ProjectY', 2, 'Houston', 5);

INSERT INTO Works_On0015 VALUES
(1, 1, 12),
(2, 1, 10),
(3, 2, 12);

INSERT INTO Dependent0015 VALUES
(3, 'Dependent1', 'M', NULL, 'Reference'),
(1, 'John A. Kool', 'M', NULL, 'Reference');

ALTER TABLE Employee0015 ADD CONSTRAINT FOREIGN KEY(super_ssn) REFERENCES Employee0015(ssn) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Employee0015 ADD CONSTRAINT FOREIGN KEY(dno) REFERENCES Department0015(dnumber) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Department0015 add constraint FOREIGN KEY(mgr_ssn) REFERENCES Employee0015(ssn) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Dept_Locations0015 ADD constraint FOREIGN KEY(dnumber) REFERENCES Department0015(dnumber) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Project0015 ADD CONSTRAINT FOREIGN KEY(dnum) REFERENCES Department0015(dnumber) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Works_On0015 ADD CONSTRAINT FOREIGN KEY(essn) REFERENCES Employee0015(ssn) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Works_On0015 ADD CONSTRAINT FOREIGN KEY(pno) REFERENCES Project0015(pnumber) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Dependent0015 ADD CONSTRAINT FOREIGN KEY(essn) REFERENCES Employee0015(ssn) ON UPDATE CASCADE ON DELETE CASCADE;

SELECT * FROM Employee0015;
SELECT * FROM Department0015;
SELECT * FROM Dept_Locations0015;
SELECT * FROM Project0015;
SELECT * FROM Works_On0015;
SELECT * FROM Dependent0015;
